//
//  RCDCommonString.h
//  SealTalk
//
//  Created by Sin on 2019/6/3.
//  Copyright © 2019 RongCloud. All rights reserved.
//

#ifndef RCDCommonString_h
#define RCDCommonString_h

#define RCDIMTokenKey @"userToken"
#define RCDAppKeyKey @"appKey"
#define RCDUserIdKey @"userId"
#define RCDPhoneKey @"phoneNumber"
#define RCDUserNickNameKey @"userNickName"
#define RCDUserPortraitUriKey @"userPortraitUri"
#define RCDSquareInfoListKey @"SquareInfoList"
#define RCDQiNiuDomainKey @"QiNiuDomain"
#define RCDApplistURLKey @"applistURL"
#define RCDNeedUpdateKey @"isNeedUpdate"
#define RCDDisplayIDKey @"isDisplayID"
#define RCDCurrentCountryKey @"currentCountry"
#define RCDStayAfterJoinChatRoomFailedKey @"stayAfterJoinChatRoomFailed"
#define RCDDebugDataStatisticsKey @"RCDDebugDataStatistics"
#define RCDDebugBurnMessageKey @"RCDDebugBurnMessage"
#define RCDDebugSendCombineMessageKey @"RCDDebugSendCombineMessage"
#define RCDUserCookiesKey @"UserCookies"
#define RCDDisplayOnlineStatusKey @"isDisplayOnlineStatus"
#define RCDSwitchTestEnvKey @"RCDSwitchTestEnvKey"
#define RCDCookieKey @"Cookie"
#define RCDDemoServerKey @"RCDDemoServer"
#define RCDGroupInfoUpdateKey @"UpdateGroupInfo"
#define RCDGroupMemberUpdateKey @"UpdateGroupMember"
#define RCDGroupNoticeUpdateKey @"UpdateGroupNotice"
#define RCDSealTalkNumberKey @"RCDSealTalkNumber"
#define RCDUserGenderKey @"RCDUserGender"
#define RCDUserPrivacyMobileSearchKey @"RCDUserPrivacyMobileSearchKey"
#define RCDUserPrivacySTAccountSearchKey @"RCDUserPrivacySTAccountSearchKey"
#define RCDUserPrivacyFriendVerifyKey @"RCDUserPrivacyFriendVerifyKey"
#define RCDUserPrivacyGroupVerifyKey @"RCDUserPrivacyFriendVerifyKey"
#define RCDContactsAuthStateChangeKey @"RCDContactsAuthStateChangeKey"
#define RCDContactsRequestKey @"RCDContactsRequestKey"
#define RCDContactsUpdateUIKey @"RCDContactsUpdateUIKey"
#define RCDChatBackgroundKey @"RCDChatBackgroundKey"
#define RCDChatBackgroundFromAlbum @"RCDChatBackgroundFromAlbum"
#define RCDChatBackgroundImageDataKey @"RCDChatBackgroundImageDataKey"
#define RCDChatroomDefalutHistoryMessageCountKey @"ChatroomDefaultHistoryMessageCount"
#define RCDGroupClearMessageKey @"RCDGroupClearMessageKey"
#define RCDCurrentPushLauguageCodeKey @"RCDCurrentPushLauguageCodeKey"
#define RCDDebugDisableSystemEmoji @"RCDDebugDisableSystemEmoji"
#define RCDDebugUtralGroupSyncKey  @"RCDDebugUtralGroupSyncKey"
#define RCDDebugInputKeyboardUIKey  @"RCDDebugInputKeyboardUIKey"
#define RCDDebugUltraGroupEnable @"RCDDebugUltraGroupEnable"
#define RCDDebugTextAsyncDrawEnable @"RCDDebugTextAsyncDrawEnable"
#define RCDDebugCommonPhrasesEnable @"RCDDebugCommonPhrasesEnable"
#define RCDDebugHidePortraitEnable @"RCDDebugHidePortraitEnable"
#define RCDDeviceTokenKey @"RCDDeviceTokenKey"
#define RCDWormholeKey @"wormhole"
#define RCDAppLaunchingIdentifierKey @"RCDAppLaunchingIdentifierKey"
#define RCDPushExtensionIdentifierKey @"RCDPushExtensionIdentifierKey"
#define RCDDebugEnableCustomEmoji @"RCDDebugEnableCustomEmoji"
#define RCDDebugDisableEmojiBtn @"RCDDebugDisableEmojiBtn"
#define RCDDebugDisableCheckDupMessage @"RCDDebugDisableCheckDupMessage"
#define RCDDebugEnableRealTimeLocation @"RCDDebugEnableRealTimeLocation"
#define RCDDebugInterceptWillSendCombineFuntion @"RCDDebugInterceptWillSendCombineFuntion"
#define RCDDebugDisplayUserName @"RCDDebugDisplayUserName"
#define RCDDebugBlockedCommonPhrasesButton @"RCDDebugBlockedCommonPhrasesButton"
#define RCDDebugDisableDeleteRemoteMessage @"RCDDebugDisableDeleteRemoteMessage"
#define RCDDebugENABLE_STATICCONF_TEST @"RCDDebugENABLE_STATICCONF_TEST"

#endif /* RCDCommonString_h */
