
platform :ios, '9.0'
inhibit_all_warnings!

def im
  pod 'RongCloudIM/IMLibCore', '5.7.7'
  pod 'RongCloudIM/IMLib', '5.7.7'
  pod 'RongCloudIM/IMKit', '5.7.7'
  pod 'RongCloudIM/RongSticker', '5.7.7'
  pod 'RongCloudIM/Sight', '5.7.7'
  pod 'RongCloudIM/ContactCard', '5.7.7'
  pod 'RongCloudIM/LocationKit', '5.7.7'
end

target 'SealTalk' do
  use_frameworks!
  pod 'Masonry', '1.1.0'
  pod 'AFNetworking', '4.0.1'
  pod 'FMDB','2.7.5'
  pod 'GCDWebServer/Core','3.5.2'
  pod 'GCDWebServer/WebDAV','3.5.2'
  pod 'GCDWebServer/WebUploader','3.5.2'
  pod 'ZXingObjC', '3.6.5'
  pod 'MBProgressHUD', '1.1.0'
  pod 'SSZipArchive', '2.2.2'
  pod 'SDWebImage', '5.0.6'
  pod 'Bugly', '2.5.93'
  pod 'UMAPM', '1.9.0'
  pod 'UMCCommon', '7.3.7'

  pod 'DQAlertView', '1.3.0'
  pod 'MMWormhole', '~> 2.0.0'
  
  pod 'DoraemonKit/Core', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  pod 'DoraemonKit/WithLoad', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  pod 'DoraemonKit/WithMLeaksFinder', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  
  im
  
  pod 'RongCloudRTC/RongCallLib', '~> 5.3.5'
  pod 'RongCloudRTC/RongCallKit', '~> 5.3.5'
end

target "SealTalkNotificationService" do
  use_frameworks!
  pod 'MMWormhole', '~> 2.0.0'
  
  im
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end
