source 'https://github.com/CocoaPods/Specs.git'
target 'SealTalk' do
  use_frameworks!
  pod 'Masonry', '1.1.0'
  pod 'AFNetworking', '4.0.1'
  pod 'FMDB','2.7.5'
  pod 'GCDWebServer/Core','3.5.2'
  pod 'GCDWebServer/WebDAV','3.5.2'
  pod 'GCDWebServer/WebUploader','3.5.2'
  pod 'ZXingObjC', '3.6.5'
  pod 'MBProgressHUD', '1.1.0'
  pod 'SSZipArchive', '2.2.2'
  pod 'SDWebImage', '5.0.6'
  pod 'Bugly', '2.5.91'
  pod 'UMCCommon', '7.3.5'

  pod 'DQAlertView', '1.3.0'
  pod 'MMWormhole', '~> 2.0.0'
  
  pod 'DoraemonKit/Core', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  pod 'DoraemonKit/WithGPS', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  pod 'DoraemonKit/WithLoad', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  pod 'DoraemonKit/WithMLeaksFinder', '3.0.2', :configurations => ['Debug', 'AppStoreDebug']
  
  pod 'RongCloudIM/IMLib', '5.3.2'
  pod 'RongCloudIM/IMKit', '5.3.2'
  pod 'RongCloudIM/RongSticker', '5.3.2'
  pod 'RongCloudIM/Sight', '5.3.2'
  pod 'RongCloudIM/ContactCard', '5.3.2'
  pod 'RongCloudIM/LocationKit', '5.3.2'
  pod 'RongCloudRTC/RongCallLib'
  pod 'RongCloudRTC/RongCallKit'
end

target "SealTalkNotificationService" do
  use_frameworks!
  pod 'MMWormhole', '~> 2.0.0'
end

